apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysample-allication
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chetana027/sample_app.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mysampleapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true